language: python

sudo: required

install:
  - sudo apt-get install poppler-utils
  - pip install tox

matrix:
  include:
    - python: 3.4
      env: ENV=py34-1.9
    - python: 3.5
      env: ENV=py35-1.10
    - python: 3.6
      env: ENV=py36-1.11
    - python: 3.4
      env: ENV=py34-1.9
    - python: 3.5
      env: ENV=py35-1.10
    - python: 3.6
      env: ENV=py36-1.11
    - python: 3.4
      env: ENV=py34-1.9
    - python: 3.5
      env: ENV=py35-1.10
    - python: 3.6
      env: ENV=py36-1.11
    - python: 3.4
      env: ENV=flake8

script: tox -e $ENV
