language: python

sudo: required

python:
  - "3.4"

install:
  - pip install -r requirements/test.txt
  - sudo apt-get install poppler-utils

env:
  matrix:
    - TARGET=test
    - TARGET=lint

script: make $TARGET

after_success:
  - bash <(curl -s https://codecov.io/bash)
